### ISSUE TITLE
Feature Request: Add Option to Customize Training Iteration Steps

### ISSUE THREAD

**Issue by CodFish124** [xverse-engine/XV3DGS-UEPlugin#11]
Hello Xverse,

I've been using XV3DGS-UEPlugin for a while now and I'm really impressed with its capabilities.

However, I've encountered a limitation regarding the inability to adjust the training iteration steps. Currently, the plugin runs for a fixed number of iterations, but for my use case, I need the flexibility to alter this based on different datasets and project requirements. 

- **(The default number of steps for training is 12300)**

Having the option to customize the number of training iterations would greatly enhance the plugin's utility, allowing users like myself to tailor the training process more closely to our specific needs.

Thank you for considering this request. I'm looking forward to any updates on this and am happy to provide more information if needed.

Best regards!

**Comment by lxk121lalala** [comment]
Thank you for your feedback, we will release a new version next week, which will expose more training parameters to users


best




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xverse-engine/XV3DGS-UEPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月5日(星期五) 晚上8:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xverse-engine/XV3DGS-UEPlugin] Feature Request: Add Option to Customize Training Iteration Steps (Issue #11)





 
Hello Xverse,
 
I've been using XV3DGS-UEPlugin for a while now and I'm really impressed with its capabilities.
 
However, I've encountered a limitation regarding the inability to adjust the training iteration steps. Currently, the plugin runs for a fixed number of iterations, but for my use case, I need the flexibility to alter this based on different datasets and project requirements.
  
(The default number of steps for training is 12300)
  
Having the option to customize the number of training iterations would greatly enhance the plugin's utility, allowing users like myself to tailor the training process more closely to our specific needs.
 
Thank you for considering this request. I'm looking forward to any updates on this and am happy to provide more information if needed.
 
Best regards!

**Comment by lxk121lalala** [comment]
> Hello Xverse,
> 
> I've been using XV3DGS-UEPlugin for a while now and I'm really impressed with its capabilities.
> 
> However, I've encountered a limitation regarding the inability to adjust the training iteration steps. Currently, the plugin runs for a fixed number of iterations, but for my use case, I need the flexibility to alter this based on different datasets and project requirements.
> 
> * **(The default number of steps for training is 12300)**
> 
> Having the option to customize the number of training iterations would greatly enhance the plugin's utility, allowing users like myself to tailor the training process more closely to our specific needs.
> 
> Thank you for considering this request. I'm looking forward to any updates on this and am happy to provide more information if needed.
> 
> Best regards!

We fixed this problem in v1.1.1 version release, you can download our new version to try it out
