### ISSUE TITLE
3DGS-File trained with nerfstudio is not working with ue5.3

### ISSUE THREAD

**Issue by giscap** [xverse-engine/XV3DGS-UEPlugin#13]
FYI

I trained a 3DGS-Modell with Nerfstudio which i loaded through your plugin to ue5.3 but the loaded Modell is super laggy and has fales colors. Somehow the turnaraound explained below fixed the problem:

SOLUTION: import it to blender with the gaussian-splatting addon from here:
https://github.com/ReshotAI/gaussian-splatting-blender-addon/blob/master/blender-addon/plyfile.py
and exporting it again. It creates a file with the same size than the original one from nerfstudio, but can now be loaded corretly to XV3DGS and ue5.3

thx for your work

**Comment by Flupke70** [comment]
I have the same problem here.. You found any solution for this ? 
Thanks
