### ISSUE TITLE
PLY file import error

### ISSUE THREAD

**Issue by breezanil** [xverse-engine/XV3DGS-UEPlugin#16]
Hello, 
I tried to import ply Gaussian Splat file, but I get an error 
"ply properties header format invalid, pls check it first"

The Gaussian Splat file was generated with Nerfstudio, then converted into PLY through SuperPlat.

I also tried to import PLY to Blender (worked) and re export to another PLY, but it still gets an error in XV3DGS plugin.

Unreal version 5.3.2
XV3DGS plugin  1.0
Windows 11

Thanks a lot for your help.
breezanil

**Comment by IvanTymoshenko** [comment]
Same issue here. Error code is the same. "ply properties header format invalid, pls check it first"
UE Version: 5.2.1
XV3DGS Plugin 1.1.1
The Gaussian Splat file was generated with Nerfstudio, then exported as PLY from Nerfstudio. I can provide all necessary files if needed.

**Comment by IvanTymoshenko** [comment]
UPDATE: Your DEMO file is working. It has something to do with PLY version maybe...

**Comment by IvanTymoshenko** [comment]
Hi @lxk121lalala . Can we get some clarification on that topic? Maybe we need to use another way of generating Gaussian splats instead of nerfstudio? Just wondering on what is your approach?

**Comment by lxk121lalala** [comment]
We added support for the generic ply header file in the just released v1.1.2 plugin, please try again and contact me if there are any bugs

> Same issue here. Error code is the same. "ply properties header format invalid, pls check it first" UE Version: 5.2.1 XV3DGS Plugin 1.1.1 The Gaussian Splat file was generated with Nerfstudio, then exported as PLY from Nerfstudio. I can provide all necessary files if needed.

We added support for the generic ply header file in the just released v1.1.2 plugin, please try again and contact me if there are any bugs

**Comment by lxk121lalala** [comment]
> Same issue here. Error code is the same. "ply properties header format invalid, pls check it first" UE Version: 5.2.1 XV3DGS Plugin 1.1.1 The Gaussian Splat file was generated with Nerfstudio, then exported as PLY from Nerfstudio. I can provide all necessary files if needed.

We added support for the generic ply header file in the just released v1.1.2 plugin, please try again and contact me if there are any bugs

**Comment by IvanTymoshenko** [comment]
Just tested it. Works for me! Thank you! I will test your plugin regularly and try to provide good feedback as well! Thank you for your work!

**Comment by 4skar** [comment]
Hi, I am having the same import error message ''ply properties header format invalid, pls check it first".
UE Version: 5.3.2
XV3DGS Plugin 1.1.3
The gaussian splat was generated and exported from Polycam. 

Thank you for your help!

**Comment by LowlyAnimalOfficial** [comment]
Hey @4skar I fixed the problem by converting the .ply file to cloudcompare and then back to .ply by using https://github.com/francescofugazzi/3dgsconverter

I hope it will work for you too!
