### ISSUE TITLE
UE4 support

### ISSUE THREAD

**Issue by LaFeuilleMorte** [xverse-engine/XV3DGS-UEPlugin#24]
Thank you for the amazing work. I' m currently working on UE4.27 and I want to use this plugin in UE4. Will this plugin support UE4 in the future. Or Is it possible that I transplant it into UE4 ?

**Comment by lxk121lalala** [comment]
We haven't tested it on UE4, and currently. Perhaps you could try reimplementing it using UE4's Niagara.
