### ISSUE TITLE
Double/Incorrect Transformations

### ISSUE THREAD

**Issue by GilHacco** [xverse-engine/XV3DGS-UEPlugin#3]
**Describe the bug**
When attempting to translate/move the BPGaussianActor in the scene, the Niagara particles will double-transform and if the object is rotated, the particles will transform on the incorrect axis when moved.

**To Reproduce**
1. Load a .ply into the workspace and drag blueprint into scene
2. Switch view to orthographic front/side view
3. Translate the blueprint up and down with the manipulator tool 
4. notice the particles are moving 2x as fast as the manipulator tool
5. reset position to 0, and rotate the blueprint 90 degrees on the Y axis
6. Translate the blue print up and down in world space
7. notice the actor is moving on multiple axis'

**Expected behavior**
The niagara particles should be inheriting the precise location of the root component, and not drift away from it when transforming the actor.

**Desktop (please complete the following information):**
 - OS: Win10
 - UE Version: 5.3.2

**Additional context**
I could be wrong, but perhaps this has to do with a problem converting local transforms to world space?

**Comment by lxk121lalala** [comment]
Thanks for your feedback, we have verified this bug, we will fix it in the next submission.

**Comment by lxk121lalala** [comment]
Hello, we have resolved this issue in the v1.1.0 version. Feel free to give it a try.
