### ISSUE TITLE
使用open3d生成的点云数据不能被读取，能支持open3d生成的点云数据导入吗

### ISSUE THREAD

**Issue by xpalive** [xverse-engine/XV3DGS-UEPlugin#36]
当我使用open3d生成的以ply为后缀点云数据，通过xverse的ue插件导入到ue引擎中时被告知“ply properties header format invalid, pls checked it first”,请问哪些头属性是必须的？
下面是我通过open3d生成的ply文件的头信息
<pre>
ply
format binary_little_endian 1.0
comment Created by Open3D
element vertex 921600
property double x
property double y
property double z
property uchar red
property uchar green
property uchar blue
end_header
</pre>
以下是示例的ply文件的头信息
<pre>
ply
format binary_little_endian 1.0
element vertex 206346
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float f_rest_0
property float f_rest_1
property float f_rest_2
property float f_rest_3
property float f_rest_4
property float f_rest_5
property float f_rest_6
property float f_rest_7
property float f_rest_8
property float f_rest_9
property float f_rest_10
property float f_rest_11
property float f_rest_12
property float f_rest_13
property float f_rest_14
property float f_rest_15
property float f_rest_16
property float f_rest_17
property float f_rest_18
property float f_rest_19
property float f_rest_20
property float f_rest_21
property float f_rest_22
property float f_rest_23
property float f_rest_24
property float f_rest_25
property float f_rest_26
property float f_rest_27
property float f_rest_28
property float f_rest_29
property float f_rest_30
property float f_rest_31
property float f_rest_32
property float f_rest_33
property float f_rest_34
property float f_rest_35
property float f_rest_36
property float f_rest_37
property float f_rest_38
property float f_rest_39
property float f_rest_40
property float f_rest_41
property float f_rest_42
property float f_rest_43
property float f_rest_44
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header
</pre>

**Comment by wsAndy** [comment]
如何只用于加载ply文件（非gs输出），建议直接拖入ue场景而不是用插件的”import ply“按钮。

**Comment by basil-hayden** [comment]
这个插件是用来导入3dgs生成的点云的，你用这个插件导入open3d的点云就不对
