### ISSUE TITLE
Where is the demo project?

### ISSUE THREAD

**Issue by 3Duke** [xverse-engine/XV3DGS-UEPlugin#5]
In the main branch there isn't any demo project as instructs says, and some links drives you to a 404 page...please, I need a demo project file to start if possible

**Comment by lxk121lalala** [comment]
you can download packaged project and plugins from the Releases
https://github.com/xverse-engine/XV3DGS-UEPlugin/archive/refs/tags/v1.0.1.zip

![image](https://github.com/xverse-engine/XV3DGS-UEPlugin/assets/9654139/b1e1352c-0a15-46b5-ab85-8c341301ccf1)
