### ISSUE TITLE
这是个伪开源项目, 公司网站也打不开了

### ISSUE THREAD

**Issue by tary** [xverse-engine/XV3DGS-UEPlugin#64]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wsAndy** [comment]
哪个网站打不开？

**Comment by tary** [comment]
https://xverse.cn/zh-cn, 看了下 现在可以了
